// Code generated by protoc-gen-go.
// source: pb/rate/rate.proto
// DO NOT EDIT!

/*
Package rate is a generated protocol buffer package.

It is generated from these files:
	pb/rate/rate.proto

It has these top-level messages:
	Request
	Result
*/
package rate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	SourceCurrency string `protobuf:"bytes,1,opt,name=sourceCurrency" json:"sourceCurrency,omitempty"`
	TargetCurrency string `protobuf:"bytes,2,opt,name=targetCurrency" json:"targetCurrency,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetSourceCurrency() string {
	if m != nil {
		return m.SourceCurrency
	}
	return ""
}

func (m *Request) GetTargetCurrency() string {
	if m != nil {
		return m.TargetCurrency
	}
	return ""
}

type Result struct {
	Rate float64 `protobuf:"fixed64,1,opt,name=rate" json:"rate,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Result) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "rate.Request")
	proto.RegisterType((*Result)(nil), "rate.Result")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Rate service

type RateClient interface {
	// GetRates returns the exchange rate for the given currencies
	GetRates(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
}

type rateClient struct {
	cc *grpc.ClientConn
}

func NewRateClient(cc *grpc.ClientConn) RateClient {
	return &rateClient{cc}
}

func (c *rateClient) GetRates(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/rate.Rate/GetRates", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rate service

type RateServer interface {
	// GetRates returns the exchange rate for the given currencies
	GetRates(context.Context, *Request) (*Result, error)
}

func RegisterRateServer(s *grpc.Server, srv RateServer) {
	s.RegisterService(&_Rate_serviceDesc, srv)
}

func _Rate_GetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateServer).GetRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rate.Rate/GetRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateServer).GetRates(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rate.Rate",
	HandlerType: (*RateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRates",
			Handler:    _Rate_GetRates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/rate/rate.proto",
}

func init() { proto.RegisterFile("pb/rate/rate.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x48, 0xd2, 0x2f,
	0x4a, 0x2c, 0x49, 0x05, 0x13, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x52,
	0x24, 0x17, 0x7b, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x1a, 0x17, 0x5f, 0x71, 0x7e,
	0x69, 0x51, 0x72, 0xaa, 0x73, 0x69, 0x51, 0x51, 0x6a, 0x5e, 0x72, 0xa5, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x67, 0x10, 0x9a, 0x28, 0x48, 0x5d, 0x49, 0x62, 0x51, 0x7a, 0x6a, 0x09, 0x5c, 0x1d, 0x13,
	0x44, 0x1d, 0xaa, 0xa8, 0x92, 0x0c, 0x17, 0x5b, 0x50, 0x6a, 0x71, 0x69, 0x4e, 0x89, 0x90, 0x10,
	0x17, 0xd8, 0x32, 0xb0, 0x79, 0x8c, 0x41, 0x60, 0xb6, 0x91, 0x3e, 0x17, 0x4b, 0x50, 0x62, 0x49,
	0xaa, 0x90, 0x3a, 0x17, 0x87, 0x7b, 0x6a, 0x09, 0x88, 0x59, 0x2c, 0xc4, 0xab, 0x07, 0x76, 0x1f,
	0xd4, 0x41, 0x52, 0x3c, 0x30, 0x2e, 0xc8, 0x90, 0x24, 0x36, 0xb0, 0xb3, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xcc, 0xbf, 0x2f, 0xb0, 0xcc, 0x00, 0x00, 0x00,
}
